ory/sdk

scripts/prep.sh

When calling `./scripts/generate.sh` script encounters an error due to redundant `..` present in `ory-dev` invocation

Fix `ory-dev` invocation when generating sdks

---

Dockerfile
config/client/dotnet.yml
scripts/generate.sh
scripts/release.sh

Started work on generating and pushing a dotnet package to NuGet.
This requires the `NUGET_API_KEY` environment variable to be set in CI as well as the `Ory` org to be claimed at NuGet.
Any guidance on how to test this implementation would be good, it should work right away but I haven't found a way to test it.

feat: add dotnet SDK generation

---

scripts/release.sh

I overlooked some recursion in the generation of the dotnet sdks. Who thought it would be a good idea to name the cli the same thing as the platform? 🤦‍♂️ (it's totally my own fault and it makes complete sense but this was surprisingly hard to spot 😂)
It's calling itself here: https://github.com/ory/sdk/blob/master/scripts/release.sh#L109
and here: https://github.com/ory/sdk/blob/master/scripts/release.sh#L111

fix: recursion in dotnet sdk generation

---

Dockerfile
scripts/generate.sh

This changes the Docker container to build off of `openjdk:16-slim-buster` to add ARM support for local testing on new Apple M1 silicon.
This addresses points raised in #48.

Add ARM docker support

---

.github/CODEOWNER
.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/auto_assign.yml
.github/pull_request_template.md
.github/semantic.yml
.github/workflows/closed_references.yml
.github/workflows/labels.yml
.github/workflows/stale.yml
.reference-ignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

Updated repository templates to https://github.com/ory/meta/commit/ad9a6404080b7fb14d2d265ac0a2d4b685624d9b.

chore: update repository template to ad9a6404

---

config/client/ruby.yml
scripts/prep.sh

All ruby clients are generated with a hard-coded module name "OryHydraClient", which is wrong.
For instance for Kratos client:
```ruby
module OryHydraClient
class << self
end
end
module OryKratosClient
class << self
end
end
```
This PR fixes it for all clients.
the changes.
works.
appropriate).

fix: Generate proper module name for Ruby clients

---

scripts/generate.sh

Current ory sdk for dart generation uses `dart-dio` which does not support null safety intrduced in Dart 2.12. As Flutter 3 requires Dart's null safety, it is a blocking issue for the ory sdk to not support Flutter 3. The change uses the "default" Dart generator `dart` instead of `dart-dio` 
Ory & Dart's null safety is discussed here https://github.com/ory/cloud/issues/13
I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
Full disclosure I have not tested generating Ory SDK with `dart` over `dart-dio` 🙊

fix: generate with dart instead of dart-dio [dart] 

---

scripts/generate.sh

After months of work `dart-dio` has been updated with furthered support of OAS3 https://github.com/OpenAPITools/openapi-generator/pull/12295
It would be in user's interest to use the more encompassing dart generator leveraging dio (replacement of dart's http pkg) with OAS3 polymorphism support
Previous PR to switch off `dart-dio` due to issues with not generating flutter 3 compatible code https://github.com/ory/sdk/pull/202
I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
Full disclosure I have not tested generating Ory SDK with `dart` over `dart-dio` 🙊

feat: use dart-dio now that it supports polymorphism

---

config/README.md

Context: https://github.com/ory/client-ruby/issues/2#issuecomment-1372826023
- make the documentation links more prominent in the SDK READMEs
- update to Ory Network + correct link
- move feedback to the end of document
This should lead all who are looking for docs to ory.sh/docs/sdk where there will be a table overview of all SDKs and their docs. 
closes: https://github.com/ory/client-ruby/issues/2

fix: update SDK READMEs

---

scripts/generate.sh
scripts/release.sh

Currently, we only publish the package contents to hex.pm, and no documentation.
According to hex publishing documentation https://hex.pm/docs/publish#documentation - we can publish both package and documentation by omitting the `package` part of the hex.publish command.
Elixir has a really nice online documentation platform under https://hexdocs.pm. By publishing the package and documentation, users will be able to read the generate documentation online, (e.g. at https://hexdocs.pm/ory_kratos/)
This should work out of the box, as [aeneasr](https://hex.pm/users/aeneasr) already owns the packages on hex.

docs: elixir - Publish documentation in release script 

---

Dockerfile

Was previously failing to build the docker image with
```
=> ERROR [20/25] RUN gem install bundler &&       apt-get update &&       apt-get install -y --no-install-recommends ruby-dev                                                                                                                                            3.4s
------
> [20/25] RUN gem install bundler &&       apt-get update &&       apt-get install -y --no-install-recommends ruby-dev:
------
executor failed running [/bin/sh -c gem install bundler &&       apt-get update &&       apt-get install -y --no-install-recommends ruby-dev]: exit code: 1
```
None.
I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to …

fix: pin ruby `bundler` gem to v`2.3.36`

---

config/client/dart.yml
scripts/generate.sh
scripts/prep.sh

Follow up of https://github.com/ory/sdk/pull/263
Adds the repository to the pubspec.yaml so that on pub.dev a link to the repository will be shown to users.
https://dart.dev/tools/pub/pubspec#repository
I, unfortunately, couldn't test it locally as I get errors for both the current Docker image v0.51.0 as well as a locally built image ...
Not sure if this might have to do something with my M1 MacBook?!

docs(dart): add link to source code / repository for pub.dev

---

contrib/poms/client/pom.xml
contrib/poms/hydra/pom.xml
contrib/poms/keto/pom.xml
contrib/poms/kratos/pom.xml
contrib/poms/oathkeeper/pom.xml
scripts/generate.sh

fixes https://github.com/ory/hydra-client-java/issues/19

chore: upgrade java generator to version 7.3.0

---

config/client/java.yml

Adds discriminator lookups for Java `oneOf` specs. This fixes an issue where the `oneOf` specs weren't being automatically discriminated.
Fixes https://github.com/ory/kratos/issues/3807

fix: enable discriminator lookup for java

---

scripts/generate.sh

Update open-apigenerator to 7.8.0 for dotnet to fix ApiClient issue in Blazor WASM environments
Updates open-apigenerator to 7.8.0 to include a [fix](https://github.com/OpenAPITools/openapi-generator/pull/19231) for Blazor WebAssembly where API calls trigger a `System.PlatformNotSupportedException` due to invoking a blocking wait from a WASM environment. I believe this bug could be triggered by making any call from any Ory Client class in a Blazor WebAssembly environment. As such Ory Client is unusable in Blazor WASM without this fix.

chore: update openapi-generator to 7.8.0 for dotnet

---

contrib/dotnet/ApiClientHooks.cs
scripts/generate.sh

When using Ory SDK from .NET Blazor WASM, it is necessary to call `httpRequestMessage.SetBrowserRequestCredentials(BrowserRequestCredentials.Include)` on `HttpRequestMessage` before invoking browser flows via fetch, so that cookies are included in the request and saved to the browser from the response.
Before making this PR I attempted to convince OpenAPI Generator maintainers to expose end-user-facing hooks on the generated `ApiClient`, but the implementation is taking time to work out. That is why this PR is for Ory SDK and not OpenAPI Generator.
This is a non-breaking change to add two new public properties to the `ApiClient` class `RequestHook` and `ResponseHook` which are optional actions to pre- and post-process RestClient roundtrips. This allows .NET Blazor WASM users to set a hook …

feat: expose api client hooks for dotnet

---

Makefile
contrib/fetch/src/continueWith.ts
contrib/fetch/src/error.ts
contrib/fetch/src/index.ts
contrib/fetch/src/ui.ts
contrib/fetch/src/urlHelpers.ts
contrib/fetch/src/utils.ts
package-lock.json
package.json

fix: add more typescript helpers

---

contrib/fetch/src/ui.ts

the changes.
works.
appropriate).

feat: add ui helper for div

---

scripts/generate.sh

openapi generator 7.13 disables reqwest default features which turns off the openssl dependency.
#425 
the changes.
works.
appropriate).

chore: use openapi-generator 7.13 to generate rust client

---

scripts/prep.sh

Saw a typo in the [rust client's README.md](https://github.com/ory/client-rust/blob/f4af1100978e655db278f4a175e559adf7dca6cb/README.md?plain=1#L8).
the changes.
works.
appropriate).

typo: spelling mistake in README generation
