ory/sdk

scripts/release.sh

fix: Do not commit top level directory

---

swagutil/cmd/sanitize.go
swagutil/cmd/sanitize_test.go
swagutil/cmd/stub/expected.json
swagutil/go.mod
swagutil/go.sum

fix: declare map[string]interface{} as extensible objects

---

Dockerfile
config/client/dotnet.yml
scripts/generate.sh
scripts/prep.sh
scripts/release.sh

This should fix #34
I'm excited to see what the next error will be 😅

fix: icu-libs not found when running dotnet pack

---

spec/kratos/v0.5.5-alpha.2.json

Add spec for kratos:v0.5.5-alpha.2

---

Dockerfile
spec/client/v0.0.1-alpha.16.json

the changes.
works.
appropriate).

Fix docker

---

contrib/poms/client/pom.xml
contrib/poms/hydra/pom.xml
contrib/poms/keto/pom.xml
contrib/poms/kratos/pom.xml
contrib/poms/oathkeeper/pom.xml

the changes.
works.
appropriate).

fix: update java POMs

---

README.md
scripts/test.sh

the changes.
works.
appropriate).

test: fix failure for swagger 2 go clients 

---

config/client/typescript.yml

This makes it easier to get to the source code from https://npmjs.com, and allows tools like renovatebot to find the changelog
the changes.
works.
appropriate).

chore(typescript): add repository field to package.json

---

README.md
contrib/poms/client/pom.xml
contrib/poms/hydra/pom.xml
contrib/poms/keto/pom.xml
contrib/poms/kratos/pom.xml
contrib/poms/oathkeeper/pom.xml
openapitools.json
spec/hydra/v1.11.0-pre.1.json

the changes.
works.
appropriate).

Resolve OpenAPI issues

---

scripts/prep.sh

the changes.
works.
appropriate).

fix: oathkeeper is oas3 now

---

scripts/generate.sh

the changes.
works.
appropriate).

fix: add license file to generated sdk packages closes #161

---

scripts/generate.sh

Fixes #123 again
the changes.
works.
appropriate).
The previous try ( #124 ) to fix this problem did not work as expected. This one should do the trick. This time I tested it myself, last time I did not know how to start the generation process.

fix: changes composer name to match with project name (again)

---

README.md

Tests aren't running on CircleCI anymore.
I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.

docs: remove mention of CircleCI

---

openapi/templates/rust/reqwest/api.mustache

fix: add missing rust import

---

scripts/generate.sh

Closes https://github.com/ory/hydra-client-go/issues/16

fix: use v2 for hydra

---

scripts/generate.sh

Fixes the naming of the go client to match the repositories naming scheme.
See https://ory-community.slack.com/archives/C010F7Z4XM1/p1669829690845909

fix: go client naming

---

config/client/java.yml
contrib/poms/client/pom.xml
scripts/generate.sh

chore: update java generator to 6.2.1

---

.github/conventional_commits.json
scripts/generate.sh

chore(ruby): pin 'psych' gem to 4.0.6

---

config/client/java.yml
contrib/poms/hydra/pom.xml
contrib/poms/keto/pom.xml
contrib/poms/kratos/pom.xml
contrib/poms/oathkeeper/pom.xml

chore(java): update `pom.xml` for other clients as well

---

Dockerfile

chore(dart): update dart version in oryd/sdk

---

scripts/generate.sh
scripts/test.sh

Fixes https://github.com/ory/sdk/issues/232

chore(dart): publish `*.g.dart` files to pub

---

.circleci/config.yml

chore: update sdk container version to v0.0.51 in ci

---

config/client/dart.yml
config/descriptions/client.txt
config/descriptions/hydra.txt
config/descriptions/keto.txt
config/descriptions/kratos.txt
config/descriptions/oathkeeper.txt
scripts/prep.sh

Adds the repository to the pubspec.yaml so that on pub.dev a link to the repository will be shown to users.
https://dart.dev/tools/pub/pubspec#repository
Also adds a longer, more descriptive description to the SDKs to better explain what the individual packages are about and to please pub.dev.
Feel free to adjust the description (should be longer than 60 and less than 180 chars) :) I've mostly taken it from the repo descriptions.

docs(dart): add additional metadata for pub.dev

---

spec/client/v1.1.39-alpha.0.json

feat: Add spec for client:v1.1.39-alpha.0

---

spec/hydra/v2.2.0-rc.3.json

chore: add spec for hydra:v2.2.0-rc.3

---

.gitattributes

chore: mark autogenerated files

---

scripts/generate.sh

chore: upgrade TS generator

---

.circleci/config.yml
.github/workflows/docker-ci.yml
scripts/build/install-dart.sh

(Also fixes a few minor things in the new PR docker workflow)

chore: bump release workflow image

---

scripts/release.sh

chore: temporarily disable dart publish

---

.circleci/config.yml
Dockerfile
README.md
scripts/release.sh

fix: use dart service account for publishing

---

scripts/generate.sh

chore: bump everything to 7.4.0

---

config/client/go.yml
config/client/python.yml

feat: use better lookup

---

.circleci/config.yml

the channel ID is set in the environment variables (circle ci context)

chore: add slack fail notification

---

Dockerfile

chore: upgrade dotnet to 6

---

scripts/generate.sh
scripts/release.sh
scripts/test.sh

See https://github.com/ory/sdk/issues/350

chore: disable elixir build & publish

---

config/client/typescript.yml

fix: incorrect name for axios package

---

scripts/generate.sh
scripts/release.sh
scripts/test.sh

See https://github.com/ory/sdk/issues/357

chore: disable ruby generator

---

scripts/release.sh

fix: rename typescript_fetch release command

---

.gitignore
Dockerfile
README.md
scripts/generate.sh
scripts/prep.sh

fix: elixir, python, java, and dart publishing

---

contrib/fetch/src/index.ts

chore: remove missing export

---

contrib/fetch/src/continueWith.ts

chore: use settings UI URL in continue_with handler

---

scripts/prep.sh

chore: set COMPOSER_ALLOW_SUPERUSER=1 in container

---

config/client/typescript-client-fetch.yml
config/client/typescript-fetch.yml
scripts/generate.sh

fix: add contrib only to ory network sdk

---

scripts/generate.sh

fix: network client generation order

---

clients/client/dart/.github/workflows/publish.yml
contrib/dart/.github/workflows/publish.yml
scripts/generate.sh
scripts/release.sh

chore: move dart release to its own file

---

config/client/dotnet.yml

net6 is EOL and no longer supported
the changes.
works.
appropriate).

fix: use net8 generator for csharp

---

contrib/fetch/src/flowTypes.ts

the changes.
works.
appropriate).

chore: add FlowType.Consent

---

contrib/fetch/src/flowTypes.ts

the changes.
works.
appropriate).

fix: rename FlowType.Consent to FlowType.OAuth2Consent

---

scripts/generate.sh
scripts/release.sh

the changes.
works.
appropriate).

chore: disable dotnet release

---

contrib/dart/.github/workflows/publish.yml

the changes.
works.
appropriate).

chore: add skip validation to dart publish dry run

---

contrib/dart/.github/workflows/publish.yml

the changes.
works.
appropriate).

chore: add missing version tag to setup-dart action

---

config/client/php.yml

the changes.
works.
appropriate).

fix: do not throw errors on unknown enums

---

contrib/poms/client/pom.xml
contrib/poms/hydra/pom.xml
contrib/poms/keto/pom.xml
contrib/poms/kratos/pom.xml
contrib/poms/oathkeeper/pom.xml
scripts/init.sh

the changes.
works.
appropriate).

fix: release java sdk to maven central repository
